from sqlalchemy import create_engine

from src.model.grupoconstrufacil.quotation import Quotation
from src.model.grupoconstrufacil.quotation_item import QuotationItem
from src.model.grupoconstrufacil.quotation_submission_items import QuotationSubmissionItem
from src.model.grupoconstrufacil.quotation_submissions import QuotationSubmission
from src.model.grupoconstrufacil.user import User